micronaut:
  application:
    name: micronautR2dbcMultipleDatasources
  server:
    port: 4800

datasources:
  h2-data-source:
    url: jdbc:h2:mem:sample
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
  mysql-data-source:
    url: jdbc:mysql://localhost:3306/sample
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sample
    password: secret
    schema-generate: CREATE_DROP
    dialect: MYSQL

flyway:
  datasources:
    h2-data-source:
      baseline-on-migrate: true
      enabled: true
    mysql-data-source:
      baseline-on-migrate: true
      enabled: true

r2dbc:
  datasources:
    h2-data-source:
      url: r2dbc:h2:mem:///sample
      username: sa
      password: ''
      schema-generate: CREATE_DROP
      dialect: H2
    mysql-data-source:
      url: r2dbc:mysql://localhost:3306/sample
      username: sample
      password: secret
      schema-generate: CREATE_DROP
      dialect: MYSQL
