micronaut:
  application:
    name: micronautR2dbcMultipleDatasources
  server:
    port: 4800

datasources:
  dataSourceOne:
    url: jdbc:h2:mem:dbOne
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
  dataSourceTwo:
    url: jdbc:h2:mem:dbTwo
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

flyway:
  datasources:
    dataSourceOne:
      enabled: true
    dataSourceTwo:
      enabled: true

r2dbc:
  datasources:
    dataSourceOne:
      url: r2dbc:h2:mem:///dbOne
      username: sa
      password: ''
      schema-generate: CREATE_DROP
      dialect: H2
    dataSourceTwo:
      url: r2dbc:h2:mem:///dbTwo
      username: sa
      password: ''
      schema-generate: CREATE_DROP
      dialect: H2